### ISSUE TITLE
Please tag latest version

### ISSUE THREAD

**Issue by silbinarywolf** [WPP-Public/akqa-nz-silverstripe-elastica#12]
@stecman Can you please tag the latest version?

**Comment by stecman** [comment]
@clairefinnie can you have a look at this? I can't quickly confirm that there are no breaking changes since 2.1.0 (mainly in @glenn-bautista's changes from January)

**Comment by silbinarywolf** [comment]
@stecman @clairefinnie Can you please just tag this with something?

**Comment by shane-nzer** [comment]
@silbinarywolf - I'll try to get this pushed through.

@bendubuisson and @clairefinnie - there's been 23 commits and 8 files modified with the addition of support for percolation type indices and queries. Does everyone agree this should be tagged to 2.2.0 given the new functionality?

**Comment by clairefinnie** [comment]
Woah!! Finally tagged.

So sorry for the delay peeps.

**Comment by silbinarywolf** [comment]
Aye! Thanks :)
I'll close this off!
