### ISSUE TITLE
got error in vendor/heyday/silverstripe-elastica/src/Searchable.php

### ISSUE THREAD

**Issue by sparkcom** [WPP-Public/akqa-nz-silverstripe-elastica#15]
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) i

I have to change line 120

 public function inheritedDatabaseFields()
    {
        return $this->owner::getSchema()->fieldSpecs($this->owner->getClassName());
    }

to 

 public function inheritedDatabaseFields()
    {
        return $this->owner->getSchema()->fieldSpecs($this->owner->getClassName());
    }

**Comment by clairefinnie** [comment]
howdy, got that last week but haven't had time fix it yet. Believe it is a PHP version issue.

That syntax is PHP7

What branch/tag are you on?

**Comment by robbieaverill** [comment]
I've pushed a fix to #20 for this
