### ISSUE TITLE
Cannot change mapping types without fully clearing the index

### ISSUE THREAD

**Issue by robbieaverill** [WPP-Public/akqa-nz-silverstripe-elastica#19]
Hi team,

In some situation you might not have access to the ElasticSearch instance to delete the index and recreate it. Example: SilverStripe Platform.

One example is our addons.silverstripe.org website. Here are some steps to outline [the issue I'm having with it](https://github.com/silverstripe/addons.silverstripe.org/issues/241):

(`addons` is my index name)

* `curl -XDELETE http://localhost:9200/addons` to delete the index
* Run `dev/tasks/Heyday-Elastica-ReindexTask` to set initial index schema
* `$ curl -s http://localhost:9200/addons/Addon/_mapping | jq .addons.mappings.Addon.properties.downloads` (type: string)
* Edit `Addon::getElasticaMapping()` and change `downloads` from `string` to `long`
* Run `dev/tasks/Heyday-Elastica-ReindexTask` _to update index spec_

Error occurs here:

```
[Emergency] Uncaught Elastica\Exception\ResponseException: mapper [downloads] of different type, current_type [text], merged_type [long]
```

If you have ES access you can manually clear the index to avoid this happening, but ideally the reindex task in this module would do that for us.

**Comment by sminnee** [comment]
One way to approach this would be to have a `?recreate=1` option ReindexTask that deleted any pre-existing indexes first. It would probably be slower than the current code so it might be worth avoiding baking it into every execution.

**Comment by robbieaverill** [comment]
Fair enough. I'll do that.

We can make one factual statement here though: if your index exists and you change your mapping type, it will fail. Ideally the module should handle this for you, e.g. "detected mapping type change, recreating index". I'm not experienced enough with the intricacies of this to know whether this can be done at a granular level like what happens when you change DB field types in SilverStripe, but an optional recreate argument seems like a good workaround.

**Comment by sminnee** [comment]
It looks like `ElasticaService::getIndex()->delete()` will give you what you want.

**Comment by sminnee** [comment]
You could potentially catch `Elastica\Exception\ResponseException` when calling `$this->service->define` and then, if that exception gets thrown, delete the index before redefining. That could be dangerous, however. I assume a ResponseException is thrown for any error whatsoever, and it could be a simple "connection timeout" error or something.

You could try looking for "of different type" in the exception message, but that's a bit messy. It's more likely to miss triggering the recreation than to trigger it inappropriately, though, which is safer. I'd probably avoid this approach unless it got buy-in from someone with more elasticsearch experience.

**Comment by robbieaverill** [comment]
The optional argument is a decent workaround. I think I'll enable it by default in the addons site, for example. In our case it's only about 10 seconds to reindex from scratch.

**Comment by robbieaverill** [comment]
I've made a PR at #20
