### ISSUE TITLE
RFC: Support for Elasticsearch > 5

### ISSUE THREAD

**Issue by jakxnz** [WPP-Public/akqa-nz-silverstripe-elastica#24]
Is there any love for supporting Elasticsearch > 5? Are maintainers happy to accept a changeset that breaks compatibility with 5?

**Comment by ant1234** [comment]
@jakxnz Do you have branch implementing support for > 5? I've got the module working well locally with 5.0.0 but our aws instance is running 6.7 and i'm getting issues with more than one mapping type. If you do, please point me to it :)

**Comment by jakxnz** [comment]
@ant1234, no sorry. We're using the ES 5.6 AWS service in production and have chosen to defer supporting later versions.

**Comment by tractorcow** [comment]
I'm doing a bit of work again on elasticsearch; I might take it upon myself to try to update it as far as possible (latest version is 7).

**Comment by tractorcow** [comment]
Check out https://github.com/heyday/silverstripe-elastica/pull/35 I got this working as far as indexing goes. I haven't got searching working well yet. :)

**Comment by jakxnz** [comment]
Decent! Wow, not too far removed from the current codebase. Nicely done @tractorcow

**Comment by tractorcow** [comment]
It was like 80% just cleaning stuff up. :) the only things that really changed that much were the `string` and `_type` being removed, and some changes to the middleware API.

**Comment by ant1234** [comment]
You're a hero if you get this working mate, we've had this running on 5.6 in production for year now, would be awesome to upgrade it

**Comment by tractorcow** [comment]
The branch I have up currently works; I haven't done a lot of complex queries with it, but it feels mostly upgraded.

The biggest breaking change is the deprecation of the _type field, and the new `type` field I added as a polyfill. Usercode that uses `_type` will need to be updated.

**Comment by phptek** [comment]
@jakxnz cc @tractorcow `dev-master` currently supports ES ^7. Thanks and big-up DJ respect to @tractorcow for doing a bulk of the work and to David Craig and Tim Kung for getting it over the line.

...closing.
