### ISSUE TITLE
Index doesn't pick up class Page (Page::class)

### ISSUE THREAD

**Issue by jakxnz** [WPP-Public/akqa-nz-silverstripe-elastica#31]
`silverstripe/framework: 4.4.5`
`symbiote/silverstripe-queuedjobs: 4.5.0`
`heyday/silverstripe-elastica: 3.0.0-rc2`

# Issue

Records of class `Page` are not being indexed

## Background

`ElasticaService` excludes `Page` from its indexed classes.

https://github.com/heyday/silverstripe-elastica/blob/3.0.0-rc2/src/ElasticaService.php#L428
```
    /**
     * Gets the classes which are indexed (i.e. have the extension applied).
     *
     * @return array
     */
    public function getIndexedClasses()
    {
        $classes = array();
        foreach (ClassInfo::subclassesFor(DataObject::class) as $candidate) {
            $candidateInstance = DataObject::singleton($candidate);
            if ($candidateInstance->hasExtension($this->searchableExtensionClassName) && $candidate != 'Page') {
                $classes[] = $candidate;
            }
        }
        return $classes;
    }
```

Note: `if ($candidateInstance->hasExtension($this->searchableExtensionClassName) && $candidate != 'Page') {`

# Question

Is there functional reasoning for this? In our project, including `Page` would be preferable

**Comment by phptek** [comment]
@jakxnz looks like this may have been fixed by my predecessor. Can you confirm/deny? FYI there's a newer version (still `dev-master` which you should probably be using to verify against).

**Comment by jakxnz** [comment]
@phptek, it's been 2 years: I've no idea, sorry.
