### ISSUE TITLE
elasticsearch/elasticsearch for PHP8

### ISSUE THREAD

**Issue by phptek** [WPP-Public/akqa-nz-silverstripe-elastica#38]
`elasticsearch/elasticsearch v8.0.0` supports `php ^7 || ^8` which we should consider using to reduce reliance on consuming projects having to run `--ignore-platform-reqs` in PHP8 setups.

**Comment by oddnoc** [comment]
Please do this! PHP 7 is reaching its end of life in a mere 6 months

**Comment by wilr** [comment]
Fixed in `4.1.0`
