### ISSUE TITLE
Unquoted YAML fix for v2.x ?

### ISSUE THREAD

**Issue by JamesDPC** [WPP-Public/akqa-nz-silverstripe-elastica#39]
Hi, in 3.0.0-rc3 this commit fixes unquoted yaml errors picked up in symfony/yaml > 3

https://github.com/heyday/silverstripe-elastica/commit/6494d8b6e0ccf44017ade9abbba8c42af2b5f42c

Is it possible to cherry-pick that commit and tag a 2.x release ?

The workaround when using v2 is to restrict symfony/yaml to ^3.4 at the project level.

**Comment by wilr** [comment]
Fixed in `4.1.0`
