### ISSUE TITLE
Stage content not indexed - and other functionality?

### ISSUE THREAD

**Issue by nyeholt** [WPP-Public/akqa-nz-silverstripe-elastica#6]
Hi guys, I was going to start updating our elastica module for SS4, and noticed you've already got something functional. Rather than duplicate the extra effort, I figured I'd check things out to see whether my use cases would be met, but there's a couple things that this fork isn't doing; I _think_ I can achieve things by adding in some extension points, but that may not pan out for everything. Happy to take some PRs that bring through some of this?

**Comment by stecman** [comment]
@nyeholt PRs are welcome. Best to create an issue for each feature you're going to work on so other people can see, question, comment, etc early on :+1:

**Comment by nyeholt** [comment]
Have done so!
